name: itse
version: 0.1.0.0
github: "githubuser/itse"
license: BSD3
author: "Author name here"
maintainer: "example@example.com"
copyright: "2021 Author name here"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:
  Please see the README on GitHub at <https://github.com/githubuser/itse#readme>

dependencies:
  - base >= 4.7 && < 5
  - mtl
  - transformers

library:
  source-dirs: src
  default-extensions:
    - GADTs
    - KindSignatures
    - ExplicitForAll
    - RankNTypes
    - FlexibleInstances
    - MultiParamTypeClasses
    - ScopedTypeVariables
    - LambdaCase
    - TypeFamilies
    - NamedFieldPuns
    - BlockArguments
    - PatternSynonyms

executables:
  itse-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wall
    dependencies:
      - itse

tests:
  itse-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - itse
